org.gradle.java.home=C:/Users/srjna/AppData/Local/Programs/Android Studio/jbr
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Dorg.gradle.internal.http.connectionTimeout=120000 -Dorg.gradle.internal.http.socketTimeout=120000 -XX:+HeapDumpOnOutOfMemoryError
systemProp.java.net.preferIPv4Stack=true
systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false
kotlin.incremental=false
